### ISSUE TITLE
When done with survey and starting the survey over, one returns to the finish screen and not the survey

### ISSUE THREAD

**Issue by philipwinsnes** [Toto-DAT257/Touch-Tell-App#36]

**Comment by sjohan99** [comment]
This happens because the `SurveyViewModel` (`SVM`) is not destroyed when the survey is finished.

What happens is:
1. When the last question is answered the `MutableLiveData surveyIsDone` is set to `true` in the SVM. 
2. After that the app navigates to the `DoneWithSurveyFragment`.
3. The user navigates back to `HomeFragment`
4. The user presses Start Survey in `HomeFragment`
5. `SurveyFragment` is created. When this happens, for every `LiveData` it calls `.observe()` on, it will also read that value.
6. Because the `SVM` was never destroyed, the value of `surveyIsDone` is indeed still `true`.
7. Since `surveyIsDone` is `true` the app navigates to `DoneWithSurveyFragment`.

I have two different solutions to the bug. I think Solution 2 is better since it keeps the functionality of letting the user navigate home without losing their answers.

Solution 1:
We attach the `SVM` to `SurveyFragment` instead. This means that when starting a survey the `SVM` is created anew again. The "side-effect" of this is that we lose the information we had meaning if the user navigates to `HomeFragment` during the survey, their answers are wiped.

Solution 2:
We reset necessary fields in `SVM`, that is `jsonIsReceived`, `surveyIsDone`, and `isLastQuestion`. This reset is done when the survey is finished.

In addition to this I also hide the questionText and questionFragment until the actual question is loaded. Otherwise the last question of the survey is shown until it has reloaded the first question.

Here's a video of solution 2:
https://user-images.githubusercontent.com/73998587/166916167-8ecc8fee-5e1b-4c3f-ace7-4409304921e4.mp4
